apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-sample-app
  namespace: monitoring
  labels:
    app: sample-app
spec:
  replicas: {{ .Values.sampleApp.replicaCount }}
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
        - name: sample-app
          image: "{{ .Values.sampleApp.image.repository }}:{{ .Values.sampleApp.image.tag }}"
          imagePullPolicy: {{ .Values.sampleApp.image.pullPolicy }}
          ports:
            - containerPort: 8080
