apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: thanos-compactor-data
  namespace: monitoring
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gp2
  resources:
    requests:
      storage: 20Gi