apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cAdvisor
  namespace: monitoring
  labels:
    app.kubernetes.io/name: cAdvisor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: cAdvisor
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cAdvisor
    spec:
      containers:
        - name: cadvisor
          image: gcr.io/cadvisor/cadvisor:v0.49.1
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: rootfs
              mountPath: /rootfs
              readOnly: true
            - name: varrun
              mountPath: /var/run
              readOnly: true
            - name: sys
              mountPath: /sys
              readOnly: true
            - name: docker
              mountPath: /var/lib/docker
              readOnly: true
      volumes:
        - name: rootfs
          hostPath:
            path: /
        - name: varrun
          hostPath:
            path: /var/run
        - name: sys
          hostPath:
            path: /sys
        - name: docker
          hostPath:
            path: /var/lib/docker
